version: '3.8'

services:
  config-server:
    image: config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - my-network

  task-service:
    image: task-service:latest
    container_name: task-service
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=taskManager
      - KEYCLOAK_CLIENT_ID=taskManager-backEnd
      - KEYCLOAK_CLIENT_SECRET=**********
      - KEYCLOAK_REDIRECT_URI=http://task-service:5167/login/oauth2/code/keycloak
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/taskManager
    ports:
      - "5167:5167"
    depends_on:
      - config-server
      - mysql
      - rabbitmq
      - keycloak
    networks:
      - my-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task
    ports:
      - "3366:3306"
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network

  keycloak:
    image: keycloak/keycloak:21.0.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin-password
      - KEYCLOAK_HTTP_PORT=8080
    ports:
      - "8080:8080"
    networks:
      - my-network
    command: start-dev


networks:
  my-network:
    driver: bridge
